import type { Metadata } from "next";
import StoryblokProvider from "@/components/StoryblokProvider";
import { Zilla_Slab, Figtree } from "next/font/google";
import "./globals.css";
import { fetchConfig } from "@/lib/storyblok";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const display = Zilla_Slab({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["700"],
});

const body = Figtree({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

  export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const config = (await fetchConfig()).content;
  return (
    <StoryblokProvider>
      <html
        lang="en"
        className={`{${display.variable} ${body.variable}} h-full antialiased`}
      >
        <body className="flex min-h-screen flex-col bg-white">
          <Navbar config={config} />
          <div className="flex-1">{children}</div>
          <Footer config={config} />
        </body>
      </html>
    </StoryblokProvider>
  );
}
